### PR TITLE
Bump actions/checkout from v2 to v2.3.3

### PR DESCRIPTION
**Pull request by HonkingGoose**
Latest release for actions/checkout is v2.3.3
See https://github.com/actions/checkout/releases/tag/v2.3.3 for release notes/change-log.

### CODE REVIEW

**Comment by martingjaldbaek** [comment]
Good catch! Thanks for the PR! 👍

**Comment by HonkingGoose** [comment]
I've checked if you could use the `github-actions` package ecosystem with Dependabot to deal with upgrades to the Action runners.

I suspect that Dependabot is hard-coded to only check the `.github/workflows` directory, so that won't help with this repository.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#directory

> You define the directory relative to the root of the repository for all ecosystems except GitHub Actions. For GitHub Actions, set the directory to / to check for workflow files in .github/workflows.

I hoped you might be able to do something like this in a `dependabot.yml` file in the `.github` folder:

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/combine-prs.yml"
    schedule:
      interval: "daily"
```

**Comment by martingjaldbaek** [comment]
Thanks for looking into that! I actually have a separate repo for manual testing purposes (e.g. with open dependabot PRs) where the workflow is in the `.github/workflows` so if nothing else, I can get notified there, and then update here as well.

I was also disappointed that apparently there is currently no way to publish a Workflow like this as a GitHub Action of its own - having it on the Actions Marketplace would be a nice way to help others find it more easily. So a potential future improvement would be to rewrite it as an Action (either by re-writing the branch-creation part to happen from JS, so it can be a pure JS action, or make a docker image)

**Comment by HonkingGoose** [comment]
## About getting a Starter Workflow published on GitHub

You used to be able to propose new workflows at https://github.com/actions/starter-workflows, so that they can be included into the upstream GitHub repository, and be available for others, but they're not accepting new ones right now. 

See issue 631 on that repo for more on that:

> 👋🏾 Hi there

> As you can probably tell, we haven't been very good at merging in new starter workflows in to this repository. First off I'd like to apologise to everyone who has submitted a new starter workflow. Thank you for submitting them and our apologies for not accepting them sooner.

> We'd love to have more starter workflows appear on the Actions tab, but at this time the page just doesn't work well with lots of new starter workflows. Having a team try to process and understand the starter workflows hasn't worked too well.

> Perhaps we need to make starter workflows more like the Marketplace, so a community can publish and update workflows without needing approval. That's something we are exploring for the future.

> At this time I think its unfair to starter workflow authors to submit them and then have nothing happen with them for a long period of time. Rather than create unfair expectations we are temporarily going to stop accepting new starter workflows. We will try to merge all the ones already submitted, see below 👇🏾 for that list.

> Sorry about that, but hope this is temporary and we'll figure something else out that's better for the future.

---

## About rewrite of JavaScript action

I think this is the template you can try use, if you want to make a JavaScript action:
https://github.com/actions/javascript-action

I don't know if you already found that? So I'm mentioning it here in case you haven't yet seen it. :smile:

**Comment by martingjaldbaek** [comment]
Thanks for sharing your research! :) Yeah, it seems like the platform is still evolving. For all their similarities, I'm actually kinda surprised that workflows and actions are treated as two completely different things - maybe they'll converge eventually? At any rate, I think a rewrite based on that JS action you linked is probably the most realistic way of "actionifying" the workflow for now.

**Pull request merged**
